import type { Metadata } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Footer from '../components/Footer';
import Header from '../components/Header';
import './globals.css';
import ErrorBoundary from '../components/ErrorBoundary/page';
import { LanguageProvider } from '../context/LanguageContext/LanguageContext';
import { AuthProvider } from '../context/AuthContext/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'GraphiQL',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <LanguageProvider>
      <ErrorBoundary>
        <html lang="en">
          <Head>
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <AuthProvider>
            <body suppressHydrationWarning={true} className={inter.className}>
              <Header />
              {children}
              <Footer />
            </body>
          </AuthProvider>
        </html>
      </ErrorBoundary>
    </LanguageProvider>
  );
};

export default RootLayout;
